/**
 * Parity test: web/coach.ts pickSeed must reproduce seeds/retrieve.py pull()
 * exactly. The golden fixture scripts/experiment/out/drawer-vectors.json holds
 * 16 cases ({case, seed, pool, poolIds, preference, genre,
 * expectedSeedIdSequence}) generated by gen-drawer-vectors.py with
 * `random.Random(SEED0 + case)`. Cases 0-11 drive the explicit-preference
 * two-stage drawer; cases 12-15 drive the default genre preference (specific
 * cards preferred over agnostic-only from a mixed pool) via the `genre` field.
 * Assertion mode: EXACT sequence equality, not the fallback hit-rate
 * statistical check. Exact replication is proven viable by Mt19937 below, a
 * faithful port of CPython's `random` module for the integer-seeded path this
 * fixture uses:
 *   - seeding: init_by_array (CPython uses this for ANY int seed, even small
 *     ones — NOT init_genrand), with the 19650218 base state;
 *   - .random(): genrand_res53, two 32-bit outputs combined to 53 bits;
 *   - .choice(): _randbelow(n) with `k = n.bit_length()` (not (n-1).bit_length()
 *     — the power-of-two off-by-one) and getrandbits(k) taking the TOP k bits
 *     (int32 >> (32-k)), with rejection sampling.
 * All 16 cases assert seed-by-seed id equality.
 */
import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import type { ClientSeed, Genre, Verb } from '../src/core/types';
import { pickSeed, type RngLike, type SeedPreference } from './coach';

/**
 * MT19937 with CPython's `random` module semantics for integer seeds. Implements
 * exactly the surface RngLike requires so pickSeed can consume it as the `rng`
 * argument the way retrieve.pull consumes a random.Random.
 */
class Mt19937 implements RngLike {
  private readonly mt = new Uint32Array(624);
  private idx = 624;

  constructor(seed: number) {
    this.initByArray([seed >>> 0]);
  }

  /** init_genrand(seed): the base state for init_by_array. */
  private initGenrand(seed: number): void {
    this.mt[0] = seed >>> 0;
    for (let i = 1; i < 624; i++) {
      const x = this.mt[i - 1];
      this.mt[i] = (Math.imul(1812433253, x ^ (x >>> 30)) + i) >>> 0;
    }
  }

  /** CPython init_by_array over a big-endian 32-bit key (here: [seed]). */
  private initByArray(key: number[]): void {
    this.initGenrand(19650218);
    let i = 1;
    let j = 0;
    let k = Math.max(624, key.length);
    for (; k; k--) {
      const p = this.mt[i - 1];
      this.mt[i] = (this.mt[i] ^ Math.imul(1664525, p ^ (p >>> 30))) + key[j] + j;
      this.mt[i] >>>= 0;
      i++;
      j++;
      if (i >= 624) {
        this.mt[0] = this.mt[623];
        i = 1;
      }
      if (j >= key.length) j = 0;
    }
    for (k = 623; k; k--) {
      const p = this.mt[i - 1];
      this.mt[i] = (this.mt[i] ^ Math.imul(1566083941, p ^ (p >>> 30))) - i;
      this.mt[i] >>>= 0;
      i++;
      if (i >= 624) {
        this.mt[0] = this.mt[623];
        i = 1;
      }
    }
    this.mt[0] = 0x80000000;
  }

  private twist(): void {
    for (let i = 0; i < 624; i++) {
      const y = (this.mt[i] & 0x80000000) + (this.mt[(i + 1) % 624] & 0x7fffffff);
      this.mt[i] = this.mt[(i + 397) % 624] ^ (y >>> 1);
      if (y & 1) this.mt[i] ^= 0x9908b0df;
    }
    this.idx = 0;
  }

  private int32(): number {
    if (this.idx >= 624) this.twist();
    let y = this.mt[this.idx++];
    y ^= y >>> 11;
    y ^= (y << 7) & 0x9d2c5680;
    y ^= (y << 15) & 0xefc60000;
    y ^= y >>> 18;
    return y >>> 0;
  }

  /** genrand_res53: two 32-bit outputs combined into a [0,1) float. */
  random(): number {
    const a = this.int32() >>> 5;
    const b = this.int32() >>> 6;
    return (a * 67108864.0 + b) / 9007199254740992.0;
  }

  /** getrandbits(k) for k <= 32: the TOP k bits of one 32-bit draw. */
  private getrandbits(k: number): number {
    return this.int32() >>> (32 - k);
  }

  /** _randbelow(n): rejection sampling with k = n.bit_length(). */
  private randbelow(n: number): number {
    const k = 32 - Math.clz32(n);
    let r: number;
    do {
      r = this.getrandbits(k);
    } while (r >= n);
    return r;
  }

  choice<T>(seq: T[]): T {
    return seq[this.randbelow(seq.length)];
  }
}

interface DrawerCase {
  case: number;
  seed: number;
  pool: Array<{ id: string; question: string; verb: string; genre: string[] }>;
  poolIds: string[];
  preference: { match?: string[]; weight?: number } | null;
  genre?: string | null;
  expectedSeedIdSequence: string[];
}

// vitest runs from the repo root; resolve the golden fixture relative to it.
// (import.meta.url is not a file:// URL under vitest's transform.)
const FIXTURE_PATH = 'scripts/experiment/out/drawer-vectors.json';
const CASES = JSON.parse(readFileSync(FIXTURE_PATH, 'utf8')) as DrawerCase[];

/**
 * The fixture pool is the drawer's input AFTER the caller's genre filter
 * (retrieve.pull never filters genre itself). For the explicit-preference
 * cases (no `genre` field) mark every card genre-agnostic so pickSeed's own
 * genre filter is a pass-through, isolating the drawer semantics under test
 * while keeping the pool's id/verb layout intact. The default-genre-preference
 * cases (12-15) record a `genre` and must keep their REAL genre arrays — the
 * mixed specific-vs-agnostic detection depends on them.
 */
function toClientSeeds(c: DrawerCase): ClientSeed[] {
  return c.pool.map((s) => ({
    id: s.id,
    question: s.question,
    genre: c.genre ? (s.genre as Genre[]) : ['genre-agnostic'],
    verb: s.verb as Verb,
  }));
}

/** Fixture preference {match: [verbs], weight?} -> pickSeed {verbs, weight?}. */
function toPreference(pref: DrawerCase['preference']): SeedPreference | undefined {
  if (!pref) return undefined;
  return { verbs: pref.match, weight: pref.weight };
}

describe('pickSeed parity with seeds/retrieve.py pull', () => {
  it('reproduces every golden drawer-vector case seed-for-seed', () => {
    expect(CASES.length).toBe(16);
    for (const c of CASES) {
      const seeds = toClientSeeds(c);
      const rng = new Mt19937(c.seed);
      const ids: string[] = [];
      for (let i = 0; i < c.expectedSeedIdSequence.length; i++) {
        ids.push(pickSeed(seeds, (c.genre ?? 'fiction') as Genre, toPreference(c.preference), rng).id);
      }
      expect(ids, `case ${c.case} (seed ${c.seed})`).toEqual(c.expectedSeedIdSequence);
    }
  });

  it('keeps the legacy no-preference uniform draw on the default Math.random rng', () => {
    // A preference-free call must never throw and must draw from the genre pool.
    const seeds = toClientSeeds(CASES[0]);
    const picked = pickSeed(seeds, 'fiction');
    expect(seeds.some((s) => s.id === picked.id)).toBe(true);
  });
});
